### PR TITLE
Introduced a lib

### PR DESCRIPTION
**Pull request by SfietKonstantin**
The lib export the battle feature that
is used by the visualizer in main.

### CODE REVIEW

**Comment by olafurw** [comment]
Palant did a change earlier that conflicts with yours.

**Comment by palant** [comment]
All the changes but `lib.rs` are pretty much the same as what I did in #12. The only additional change is removing `#[repr]` for `PokemonType` enum which seems unrelated.

**Comment by olafurw** [comment]
I kind of want to do #14 as a generalized abstraction.

**Comment by SfietKonstantin** [comment]
Will have a look at the conflicts.
In general, I like to have a lib splitted from a main.
The lib can encapsulate all the business logic (here, battling), while main (or mains) are about executing that logic. 
We can introduce integration tests to test the lib, or have several mains (one with nannou, one with a png exporter for example)

**Comment by olafurw** [comment]
I guess we're still in too much flux. I'm sorry. We abstracted Pokemon away from Battle. Which kinda changes how this is thought about.

**Comment by SfietKonstantin** [comment]
NP, will wait for the dust to settle a bit, but I'm curious about the abstraction on Pokemon :)

**Comment by SfietKonstantin** [comment]
3rd tentative :)

**Pull request merged**
